query getPlacesList($input: PlacesInput, $isNmap: Boolean!, $isBounds: Boolean!, $reverseGeocodingInput: ReverseGeocodingInput, $useReverseGeocode: Boolean = false) {
    businesses: places(input: $input) {
        total
        items {
            id
            name
            normalizedName
            category
            detailCid {
                c0
                c1
                c2
                c3
                __typename
            }
            categoryCodeList
            dbType
            distance
            roadAddress
            address
            fullAddress
            commonAddress
            bookingUrl
            phone
            virtualPhone
            businessHours
            daysOff
            imageUrl
            imageCount
            x
            y
            poiInfo {
                polyline {
                    shapeKey {
                        id
                        name
                        version
                        __typename
                    }
                    boundary {
                        minX
                        minY
                        maxX
                        maxY
                        __typename
                    }
                    details {
                        totalDistance
                        arrivalAddress
                        departureAddress
                        __typename
                    }
                    __typename
                }
                polygon {
                    shapeKey {
                        id
                        name
                        version
                        __typename
                    }
                    boundary {
                        minX
                        minY
                        maxX
                        maxY
                        __typename
                    }
                    __typename
                }
                __typename
            }
            subwayId
            markerId @include(if: $isNmap)
            markerLabel @include(if: $isNmap) {
                text
                style
                stylePreset
                __typename
            }
            imageMarker @include(if: $isNmap) {
                marker
                markerSelected
                __typename
            }
            oilPrice @include(if: $isNmap) {
                gasoline
                diesel
                lpg
                __typename
            }
            isPublicGas
            isDelivery
            isTableOrder
            isPreOrder
            isTakeOut
            isCvsDelivery
            hasBooking
            naverBookingCategory
            bookingDisplayName
            bookingBusinessId
            bookingVisitId
            bookingPickupId
            easyOrder {
                easyOrderId
                easyOrderCid
                businessHours {
                    weekday {
                        start
                        end
                        __typename
                    }
                    weekend {
                        start
                        end
                        __typename
                    }
                    __typename
                }
                __typename
            }
            baemin {
                businessHours {
                    deliveryTime {
                        start
                        end
                        __typename
                    }
                    closeDate {
                        start
                        end
                        __typename
                    }
                    temporaryCloseDate {
                        start
                        end
                        __typename
                    }
                    __typename
                }
                __typename
            }
            yogiyo {
                businessHours {
                    actualDeliveryTime {
                        start
                        end
                        __typename
                    }
                    bizHours {
                        start
                        end
                        __typename
                    }
                    __typename
                }
                __typename
            }
            isPollingStation
            hasNPay
            talktalkUrl
            visitorReviewCount
            visitorReviewScore
            blogCafeReviewCount
            bookingReviewCount
            streetPanorama {
                id
                pan
                tilt
                lat
                lon
                __typename
            }
            naverBookingHubId
            bookingHubUrl
            bookingHubButtonName
            newOpening
            newBusinessHours {
                status
                description
                dayOff
                dayOffDescription
                __typename
            }
            coupon {
                total
                promotions {
                    promotionSeq
                    couponSeq
                    conditionType
                    image {
                        url
                        __typename
                    }
                    title
                    description
                    type
                    couponUseType
                    __typename
                }
                __typename
            }
            __typename
        }
        optionsForMap @include(if: $isBounds) {
            ...OptionsForMap
            displayCorrectAnswer
            correctAnswerPlaceId
            __typename
        }
        searchGuide {
            queryResults {
                regions {
                    displayTitle
                    query
                    region {
                        rcode
                        __typename
                    }
                    __typename
                }
                isBusinessName
                __typename
            }
            queryIndex
            types
            __typename
        }
        queryString
        siteSort
        __typename
    }
    reverseGeocodingAddr(input: $reverseGeocodingInput) @include(if: $useReverseGeocode) {
        ...ReverseGeocodingAddr
        __typename
    }
}


fragment OptionsForMap on OptionsForMap {
    maxZoom
    minZoom
    includeMyLocation
    maxIncludePoiCount
    center
    spotId
    keepMapBounds
    __typename
}

fragment ReverseGeocodingAddr on ReverseGeocodingResult {
    rcode
    region
    __typename
}